//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System.ComponentModel.DataAnnotations;

namespace ZipCodeManager.Models
{
    using System;
    using System.Web.Mvc;
    using System.Collections.Generic;

    public partial class Zip
    {
        [Required]
        [StringLength(10, MinimumLength = 3)]
        [Display(Name = "Zip:")]
        public string ZIP1 { get; set; }
        [Required]
        [StringLength(50)]
        [Display(Name = "City:")]
        public string City { get; set; }
        [Required]
        [StringLength(2)]
        [Display(Name = "State:")]
        public string State { get; set; }
        [Display(Name = "County:")]
        public string County { get; set; }
        [Display(Name = "Latitude:")]
        public Nullable<double> Lat { get; set; }
        [Display(Name = "Longitude:")]
        public Nullable<double> Long { get; set; }
        public int id { get; set; }

    }
}